# Generated by Django 2.2.2 on 2019-06-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0002_xrequestid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortsequence',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
